services:
  meilisearch:
    image: getmeili/meilisearch:prototype-japanese-184
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
      - ./.docker/meilisearch/meilisearch.config.json:/etc/meilisearch/meilisearch.config.json
volumes:
  meilisearch_data:
